### ISSUE TITLE
Node.js Implementation

### ISSUE THREAD

**Issue by ea2305** [mayneyao/notabase#5]
Hi, first of all thanks for your work with this lib, I started looking some alternatives to fetch from notion and I discover this awesome project. Unfortunately, I was trying to implement it in the backend side with nodejs, but It seems not work as a module import. 

I tried with the base example in the readme, without luck.

```js
import Notabase from 'notabase'

// node env
// just Read public data
let nb = new Notabase()
``` 
But I got this error (module problems)

```bash
node:44077) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
/Users/elihu/Documents/notion-scraping/notabase.js:1
import Notabase from 'notabase'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

I also tried to import with "require" and assign the value to a constant but it's the same case i got the following error:

```bash
internal/modules/cjs/loader.js:1163
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/elihu/Documents/notion-scraping/node_modules/notabase/dist/index.js
require() of ES modules is not supported.
require() of /Users/elihu/Documents/notion-scraping/node_modules/notabase/dist/index.js from /Users/elihu/Documents/notion-scraping/notabase.js is an ES module file as it is a .js file whose nearest 
parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/elihu/Documents/notion-scraping/node_modules/notabase/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1163:13)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/elihu/Documents/notion-scraping/notabase.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14) {
  code: 'ERR_REQUIRE_ESM'
}
```
I have not ideas, am I missing something?

My Nodejs version is: 13.10.1

**Comment by picsoung** [comment]
hey @ea2305 

in your `package.json` file, did you add the following line?
```
"type": "module"
```

solved everything for me ;)

**Comment by ea2305** [comment]
Thanks for the answer @picsoung I'll try it
